[package]
name = "lumisync-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
axum = "0.7"
chrono = { version = "0.4", features = ["serde"] }
config.workspace = true
rumqttc = "0.24"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serialport = "4.3"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
sqlx-cli = "0.7.4"