[package]
name = "lumisync-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
argon2 = "0.5"
axum = "0.7"
axum-extra = { version = "0.9", features = ["typed-header"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
password-hash = { version = "0.5", features = ["getrandom"] }
rumqttc = "0.24"
rustls-native-certs = "0.7"
rustls-pemfile = "2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serialport = "4.3"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"
toml.workspace = true
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }