[server]
host = "127.0.0.1"
port = 3000

[logger]
level = "debug"

[gateway]
address = "127.0.0.1"
port = 1883
client_id = "client-gatewayb"

[gateway.topic]
prefix_env = "prefix-env"
prefix_country = "prefix-country"
customer_id = "customer-id"

[database]
url = "sqlite::memory:"